package View;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author theCodeMonster
 */
public class ModStockUI extends javax.swing.JFrame {

    /**
     * Creates new form ModStockUI
     */
    public ModStockUI() {
        initComponents();
        jPanel1.setBackground(new Color(0f, 0f, 0f, 0.8f));
    }
    
//==========================================Functions================================================================
    
    
    
//==========================================End Functions============================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priceBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        npriceBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        suppBox = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ItemID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 111, 110, 30));

        idBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBoxActionPerformed(evt);
            }
        });
        jPanel1.add(idBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 114, 243, 30));

        jLabel3.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 159, 140, 30));

        nameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(nameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 162, 243, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 209, 110, 30));

        quantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBoxActionPerformed(evt);
            }
        });
        jPanel1.add(quantityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 212, 243, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 259, 110, 30));

        priceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceBoxActionPerformed(evt);
            }
        });
        jPanel1.add(priceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 262, 243, 30));

        jLabel6.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Net Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 309, 110, 30));

        npriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npriceBoxActionPerformed(evt);
            }
        });
        jPanel1.add(npriceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 309, 243, 30));

        jLabel7.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Supplier");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 349, 110, 30));

        suppBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBoxActionPerformed(evt);
            }
        });
        jPanel1.add(suppBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 359, 243, 30));

        kButton1.setBorder(null);
        kButton1.setText("Update Item");
        kButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        kButton1.setkBorderRadius(50);
        kButton1.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 255, 255));
        kButton1.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        kButton3.setBorder(null);
        kButton3.setText("Add Item");
        kButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        kButton3.setkBorderRadius(50);
        kButton3.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 255, 255));
        kButton3.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton3.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 196, -1, -1));

        jLabel8.setFont(new java.awt.Font("October Condensed Devanagari", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modify Item");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 14, 243, 66));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 720, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBoxActionPerformed

    private void nameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBoxActionPerformed

    private void quantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBoxActionPerformed

    private void priceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceBoxActionPerformed

    private void npriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npriceBoxActionPerformed

    private void suppBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppBoxActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
 
//=========================================Begining of Variables=========================================
        try {

            String strItemId = idBox.getText();
            int itemID = Integer.parseInt(strItemId);
            if (strItemId.isEmpty() || strItemId.isBlank()) {
                itemID = 0;
            }

            String itemName = nameBox.getText();

            String strQuantity = quantityBox.getText();
            int quantity = Integer.parseInt(strQuantity);
            if (strQuantity.isEmpty() || strQuantity.isBlank()) {
                quantity = 0;
            }

            String strPrice = priceBox.getText();
            double price = Double.parseDouble(strPrice);
            if (strPrice.isEmpty() || strPrice.isBlank()) {
                price = 0;
            }

//                String strNetPrice = npriceBox.getText();
            double netPrice = (quantity * price);

            String supplier = suppBox.getText();
            
//=========================================End of Variables=========================================

            Connection conn;
            Statement st = null;
            int updateQuery = 0;
            ResultSet rs = null;
            // create our mysql database connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mch", "root", "");
            Class.forName("com.mysql.cj.jdbc.Driver");

            // our SQL SELECT query.
            String query = "INSERT INTO stocktable VALUES (" + itemID + ", '" + itemName + "', " + quantity + ", " + price + ", " + netPrice + ", '" + supplier + "');";
            // create the java statement
//                st = conn.createStatement(query);
            st = conn.createStatement();

            // execute the query, and get a java resultset
            updateQuery = st.executeUpdate(query);
//            rs = (ResultSet) st.executeQuery(query);

            System.out.println("Connection Successfull...3\n");

            st.close();
            conn.close();

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e);
        }
//            clearField();
        
        StockUI stock = new StockUI();
        stock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModStockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModStockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModStockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModStockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModStockUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JTextField nameBox;
    private javax.swing.JTextField npriceBox;
    private javax.swing.JTextField priceBox;
    private javax.swing.JTextField quantityBox;
    private javax.swing.JTextField suppBox;
    // End of variables declaration//GEN-END:variables
}
